Adding semantic mask support in vott-ct
microsoft/CanvasTools-for-VOTT pull request #150
Opened 2022-08-01 22:36 UTC by pritamDas9191

This PR aims to add the support of semantic masks in vott-ct repro.
Adds the use of brush and eraser control along with their size.
Initializes Konva js library to support masks
Supports scaling of konva stage and layer

Note: There will be multiple PRs in coming days/weeks which will add to this functionality
At the last we will do a major version upgrade and publish a new package.

![image](https://user-images.githubusercontent.com/29076912/182257010-644aa2e7-3ddd-4ed9-818c-c7f47f1601bf.png)

2022-08-02 16:32 UTC, wamoha submitted a review, later dismissed

2022-08-02 16:32 UTC, wamoha commented on src/canvastools/ts/CanvasTools/Core/Utils/constants.ts
> +export const EnabledMaskHostZIndex = 101;
nit: order by number?

2022-08-02 16:32 UTC, wamoha commented on src/canvastools/ts/CanvasTools/Interface/ISelectorSettings.ts
> +export enum SelectionMode { NONE, POINT, RECT, COPYRECT, POLYLINE, POLYGON, BRUSH = "brush", ERASER = "eraser" }
Where are the def's of other enums?

2022-08-02 16:40 UTC, code-vicar commented on src/canvastools/ts/CanvasTools/Selection/AreaSelector.ts
> +                this.maskSelector.enableMode(SelectionMode.BRUSH);
need conditional access here? `this.maskSelector?.enableMode(SelectionMode.BRUSH);`

2022-08-02 16:43 UTC, code-vicar commented on src/canvastools/ts/CanvasTools/Selection/AreaSelector.ts
> +                this.maskSelector.disable();
`this.maskSelector?.disable();`?

2022-08-02 16:46 UTC, code-vicar submitted a review, later dismissed

2022-08-02 17:27 UTC, Man-MSFT commented on package.json
> +    "@thi.ng/rle-pack": "^3.1.7",
Sanity check question - these are all dev deps only and we don't need in deps or peer deps?

2022-08-02 17:29 UTC, Man-MSFT commented on samples/editor-with-mask/index.html
> +<body>
I don't know how to comment on the jpgs in GitHub, but a hash of the files shows it's the same file twice. What are they for?

2022-08-02 17:33 UTC, Man-MSFT commented on src/canvastools/ts/CanvasTools/Interface/ISelectorCallbacks.ts
> +         onMaskSelection?: (enabled: boolean, mode?: MaskSelectorMode) => void
Extra whitespace

Do we run lint on this repo? If not, can we add to backlog to do so?

2022-08-02 17:35 UTC, Man-MSFT commented on src/canvastools/ts/CanvasTools/Interface/ISelectorSettings.ts
> +export enum SelectionMode { NONE, POINT, RECT, COPYRECT, POLYLINE, POLYGON, BRUSH = "brush", ERASER = "eraser" }
Yea, I think this causes a bit of confusion in usage...they should either all have it or none have it. Prefer none have it to maintain the back compat.

2022-08-02 17:35 UTC, Man-MSFT commented on src/canvastools/ts/CanvasTools/Region/Mask/MaskManager.ts
> +    private maskSelectionMode: MaskSelectorMode;
Why do only half of these have `/** */` comments?

2022-08-02 17:36 UTC, Man-MSFT commented on src/canvastools/ts/CanvasTools/Region/Mask/MaskManager.ts
> +        // explain these zIndex numbers
Is this a note for yourself or this is describing what this is doing?

2022-08-02 17:37 UTC, Man-MSFT commented on src/canvastools/ts/CanvasTools/Region/Mask/MaskManager.ts
> +    private base64EncodedMaskCursor(size): string {
There's a lot of new code here - when do you plan on adding tests?

2022-08-02 18:03 UTC, Man-MSFT submitted a review, later dismissed

2022-08-02 18:53 UTC, HarshUpadhyay-MSFT requested changes
Minor nit comments, looks good to merge once we close out the comments.

2022-08-02 18:53 UTC, HarshUpadhyay-MSFT commented on src/canvastools/ts/CanvasTools/Core/Utils/constants.ts
> +
nit: extra line?

2022-08-02 18:53 UTC, HarshUpadhyay-MSFT commented on src/canvastools/ts/CanvasTools/Region/Mask/MaskManager.ts
> +        canvas.width = size * 4 + 8;
can we assign `8` to some named constant?

2022-08-02 18:53 UTC, HarshUpadhyay-MSFT commented on src/canvastools/ts/CanvasTools/Region/Mask/MaskManager.ts
> +        const cursor = ["url('", base64, "')", " ", Math.floor(size / 2) + 4, " ", Math.floor(size / 2) + 4, ",auto"];
What does `4` represent here? I see it re-appearing in other places - should we refactor this to a named constant?

2022-08-02 18:53 UTC, HarshUpadhyay-MSFT commented on src/canvastools/ts/CanvasTools/Selection/AreaSelector.ts
> +        this.maskSelector = new MaskSelector(this.callbacks);
Since its being called right after invoking constructor we might not need the `?` on line 338

2022-08-02 18:54 UTC, HarshUpadhyay-MSFT submitted a review, later dismissed

2022-08-04 02:33 UTC, pritamDas9191 commented on src/canvastools/ts/CanvasTools/Region/Mask/MaskManager.ts
> +        const cursor = ["url('", base64, "')", " ", Math.floor(size / 2) + 4, " ", Math.floor(size / 2) + 4, ",auto"];
both 4 and 8 are numbers used to make sense of Maths around creating a circular cursor

2022-08-04 02:33 UTC, pritamDas9191 commented on src/canvastools/ts/CanvasTools/Region/Mask/MaskManager.ts
> +    private base64EncodedMaskCursor(size): string {
Added for new files

2022-08-04 02:33 UTC, pritamDas9191 commented on src/canvastools/ts/CanvasTools/Interface/ISelectorCallbacks.ts
> +         onMaskSelection?: (enabled: boolean, mode?: MaskSelectorMode) => void
we have lint that runs part of check in but looks like the lint rules are insufficient. will add more rules.

2022-08-04 02:34 UTC, pritamDas9191 commented on samples/editor-with-mask/index.html
> +<body>
It's for test purpose right now. Masks are saved from one and loaded onto another. Will remove before publishing the package

2022-08-04 02:34 UTC, pritamDas9191 commented on package.json
> +    "@thi.ng/rle-pack": "^3.1.7",
Good point. rle pack and konva should be in dependencies.

2022-08-04 04:43 UTC, HarshUpadhyay-MSFT approved these changes

2022-08-04 04:53 UTC, merged